### ISSUE TITLE
Question about the out_channels

### ISSUE THREAD

**Issue by zl1994** [jaxony/ShuffleNet#3]
Hi,
     May I ask you a question? When the stride of shuffle unit is 2,  why should the out_channels minus the in_channels?
the code in ShuffleUnit:
```python
# ensure output of concat has the same channels as 
# original output channels.
self.out_channels -= self.in_channels
```

**Comment by jaxony** [comment]
That happens when the ShuffleUnit is in `concat` mode. To make sure the number of output channels is correct, all I am essentially doing is `actual_output_channels = (specified_output_channels - input_channels) + input_channels`. `specified_output_channels - input_channels` is the number of output channels from the depthwise convolution.

**Comment by zl1994** [comment]
@jaxony nice, thank you !
